import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { reusableTemplates } from "@theholocron/astromech";
import { createGitHubClient } from "@theholocron/github-client";
import { ProviderApiError } from "@theholocron/http-client";
import type { Logger } from "@theholocron/logger";

import { getLogger } from "../logger.js";
import { event as telemetryEvent } from "../telemetry.js";

const DEFAULT_REPO = "theholocron/.github";

export type SyncGithubStatus = "ok" | "fail" | "dry-run";

export interface RunSyncGithubInput {
	/** GitHub personal access token with repo write access. */
	token: string;
	/** Target org/repo. Defaults to "theholocron/.github". */
	repo?: string;
	/**
	 * Push files to this branch instead of the default branch.
	 * If the branch doesn't exist it is created from the default branch HEAD.
	 * Combine with `createPr: true` to open a PR after the push.
	 */
	branch?: string;
	/** After pushing to `branch`, open a PR to the default branch. No-op if `branch` is unset. */
	createPr?: boolean;
	/** Commit message for the sync commit. */
	message?: string;
	dryRun?: boolean;
	/**
	 * Write generated files to this local directory instead of pushing to the GitHub API.
	 * Useful for local validation (e.g. actionlint) before a real sync run.
	 * When set, no API calls are made and token is not required.
	 */
	outputDir?: string;
	print?: (line: string) => void;
	/** Structured-logging sink — sibling of `print`. Defaults to the command-bound root. */
	logger?: Logger;
	/** Injectable for testing. */
	fetch?: typeof globalThis.fetch;
}

export interface SyncGithubReport {
	status: SyncGithubStatus;
	created: number;
	updated: number;
	unchanged: number;
	/** URL of the opened PR, when createPr is true and changes were made. */
	prUrl?: string;
	message?: string;
}

type FileBatch = Array<{ path: string; content: string }>;

/**
 * The file set `sync-github` pushes to `theholocron/.github` — the reusable
 * `workflow_call` implementations, composite actions and starter-workflow
 * metadata, generated by `@theholocron/astromech`. Secondary repos get nothing:
 * their thin callers are managed by `holocron sync --steps workflows`, which
 * executes the resolved config (regex parsing here can't resolve preset spreads
 * like `...tasks` from `nodeDocs()` — see issue #464).
 */
function buildBatch(repo: string): FileBatch {
	if (repo !== DEFAULT_REPO) return [];
	return [...reusableTemplates()].map(([path, content]) => ({ path, content }));
}

/** Git blob SHA: sha1("blob {len}\0{content}") — used to detect unchanged files. */
export function gitBlobSha(content: string): string {
	const buf = Buffer.from(content, "utf8");
	return createHash("sha1").update(`blob ${buf.length}\0`).update(buf).digest("hex");
}

export async function runSyncGithub(input: RunSyncGithubInput): Promise<SyncGithubReport> {
	const print = input.print ?? ((line: string) => console.log(line));
	const logger = input.logger ?? getLogger();
	const repo = input.repo ?? DEFAULT_REPO;
	const { token, dryRun = false, branch, createPr = false } = input;
	const message = input.message ?? `chore: sync from theholocron/holocron`;

	const client = createGitHubClient({ token, fetch: input.fetch });

	print(`holocron sync-github${dryRun ? " (dry-run)" : ""}`);
	print(`  repo:   ${repo}`);
	if (branch) print(`  branch: ${branch}`);
	print("");

	logger.info({ repo, branch, createPr: createPr || undefined, dryRun: dryRun || undefined }, "sync-github: start");

	/** Single exit point — one structured line per invocation, whatever the path. */
	const done = (r: SyncGithubReport): SyncGithubReport => {
		logger[r.status === "fail" ? "warn" : "info"](
			{
				repo,
				status: r.status,
				created: r.created,
				updated: r.updated,
				unchanged: r.unchanged,
				...(r.message ? { reason: r.message } : {}),
				...(r.prUrl ? { pr: r.prUrl } : {}),
			},
			"sync-github: done"
		);
		telemetryEvent("sync_github_run", {
			repo,
			status: r.status,
			...(branch ? { branch } : {}),
			repos_targeted: 1,
			files_changed: r.created + r.updated,
			pr_opened: Boolean(r.prUrl),
		});
		return r;
	};

	// ── output-dir: write all files to disk without any API calls ───────────
	if (input.outputDir) {
		const batch = buildBatch(repo);
		for (const file of batch) {
			const dest = join(input.outputDir, file.path);
			mkdirSync(dirname(dest), { recursive: true });
			writeFileSync(dest, file.content, "utf8");
		}
		print(`  ${batch.length} files written to ${input.outputDir}`);
		return done({ status: "ok", created: batch.length, updated: 0, unchanged: 0 });
	}

	// ── 1. Resolve target branch ─────────────────────────────────────────────
	let targetBranch = branch;
	let defaultBranch: string | undefined;
	if (!targetBranch || createPr) {
		try {
			const repoData = await client.repos.getRepo(repo);
			defaultBranch = repoData.default_branch;
			if (!targetBranch) targetBranch = defaultBranch;
		} catch {
			const msg = "failed to fetch repo metadata";
			print(`  ✗ ${msg}`);
			return done({ status: "fail", created: 0, updated: 0, unchanged: 0, message: msg });
		}
	}

	// ── 2. Get HEAD commit → base tree ───────────────────────────────────────
	const baseBranch = createPr && defaultBranch ? defaultBranch : targetBranch!;
	let headSha: string;
	let baseTreeSha: string;
	let existingBlobs: Map<string, string>;
	try {
		const ref = await client.git.getRef(repo, baseBranch);
		headSha = ref.object.sha;
		const commit = await client.git.getCommit(repo, headSha);
		baseTreeSha = commit.tree.sha;
		const treeData = await client.git.getTree(repo, baseTreeSha, true);
		existingBlobs = new Map(treeData.tree.filter((i) => i.type === "blob").map((i) => [i.path, i.sha]));
	} catch (err) {
		const msg = err instanceof Error ? err.message : `Branch ${baseBranch} not found`;
		print(`  ✗ ${msg}`);
		return done({ status: "fail", created: 0, updated: 0, unchanged: 0, message: msg });
	}

	// ── 3. Build file batch ─────────────────────────────────────────────────
	// Secondary-repo thin callers are managed by `holocron sync --steps workflows`.
	const batch = buildBatch(repo);

	// ── 5. Detect changes ────────────────────────────────────────────────────
	let created = 0;
	let updated = 0;
	let unchanged = 0;
	const changedFiles: Array<{ path: string; content: string }> = [];

	for (const file of batch) {
		const localSha = gitBlobSha(file.content);
		const existingSha = existingBlobs.get(file.path);

		if (existingSha === localSha) {
			print(`  · unchanged  ${file.path}`);
			unchanged++;
		} else if (existingSha) {
			print(`  ${dryRun ? "~" : "✓"} updated  ${file.path}`);
			logger.debug({ file: file.path, change: "updated" }, "sync-github: file");
			updated++;
			if (!dryRun) changedFiles.push(file);
		} else {
			print(`  ${dryRun ? "~" : "✓"} created  ${file.path}`);
			logger.debug({ file: file.path, change: "created" }, "sync-github: file");
			created++;
			if (!dryRun) changedFiles.push(file);
		}
	}

	print("");
	print(`  ${created} created, ${updated} updated, ${unchanged} unchanged`);

	if (dryRun || changedFiles.length === 0) {
		return done({ status: dryRun ? "dry-run" : "ok", created, updated, unchanged });
	}

	// ── 6. Create blobs for changed files ────────────────────────────────────
	const treeEntries: Array<{ path: string; mode: string; type: string; sha: string }> = [];
	for (const file of changedFiles) {
		try {
			const blob = await client.git.createBlob(repo, file.content);
			treeEntries.push({ path: file.path, mode: "100644", type: "blob", sha: blob.sha });
		} catch (err) {
			const msg = `failed to create blob for ${file.path}: ${err instanceof Error ? err.message : String(err)}`;
			print(`  ✗ ${msg}`);
			return done({ status: "fail", created, updated, unchanged, message: msg });
		}
	}

	// ── 7. Create tree ───────────────────────────────────────────────────────
	let newTreeSha: string;
	try {
		const newTree = await client.git.createTree(repo, treeEntries, baseTreeSha);
		newTreeSha = newTree.sha;
	} catch (err) {
		const msg = `failed to create tree: ${err instanceof Error ? err.message : String(err)}`;
		print(`  ✗ ${msg}`);
		return done({ status: "fail", created, updated, unchanged, message: msg });
	}

	// ── 8. Create commit ─────────────────────────────────────────────────────
	let newCommitSha: string;
	try {
		const newCommit = await client.git.createCommit(repo, message, newTreeSha, [headSha]);
		newCommitSha = newCommit.sha;
	} catch (err) {
		const msg = `failed to create commit: ${err instanceof Error ? err.message : String(err)}`;
		print(`  ✗ ${msg}`);
		return done({ status: "fail", created, updated, unchanged, message: msg });
	}

	// ── 9. Update (or create) branch ref ────────────────────────────────────
	try {
		if (createPr && branch) {
			try {
				await client.git.createRef(repo, `refs/heads/${branch}`, newCommitSha);
			} catch (err) {
				if (!(err instanceof ProviderApiError) || err.status !== 422) throw err;
				// Branch already exists from a previous partial run — force-update it.
				await client.git.updateRef(repo, `heads/${branch}`, newCommitSha, true);
			}
		} else {
			await client.git.updateRef(repo, `heads/${targetBranch!}`, newCommitSha);
		}
	} catch (err) {
		const msg = `failed to update ref: ${err instanceof Error ? err.message : String(err)}`;
		print(`  ✗ ${msg}`);
		return done({ status: "fail", created, updated, unchanged, message: msg });
	}

	// ── 10. Open PR if requested ─────────────────────────────────────────────
	let prUrl: string | undefined;
	if (branch && createPr && !dryRun) {
		try {
			const pr = await client.git.createPull(repo, {
				title: message.split("\n")[0]!,
				head: branch,
				base: "main",
				body: "Auto-generated by `holocron sync-github`. Review and merge to apply template updates.",
			});
			prUrl = pr.html_url;
			print(`  → PR opened: ${prUrl}`);
		} catch (err) {
			const alreadyExists =
				err instanceof ProviderApiError && err.status === 422 && String(err.details).includes("already exists");
			if (alreadyExists) {
				print(`  → PR already open for ${branch} — branch updated, ready to merge`);
			} else {
				print(`  ⚠ PR creation failed: ${err instanceof Error ? err.message : String(err)}`);
			}
		}
	}

	return done({ status: "ok", created, updated, unchanged, prUrl });
}
