/* eslint-disable */
// devmoji.config.cjs — generated by holocron setup, do not edit
// https://github.com/folke/devmoji
const pkg = require("@theholocron/devmoji-config");
module.exports = pkg.default ?? pkg;
