name: PR Bookkeeping

on:
  workflow_call:
    inputs:
      configuration-path:
        description: Path to the labeler configuration file in the calling repo
        type: string
        required: false
        default: .github/labeler.yml

jobs:
  label:
    name: Add Labels to PRs
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        with:
          configuration-path: ${{ inputs.configuration-path }}
          include-title: 1
          include-body: 0
          sync-labels: 1
          enable-versioned-regex: 0
          repo-token: ${{ github.token }}
