name: Test

on:
  workflow_call:
    inputs:
      test-command:
        description: Command to run tests with coverage
        type: string
        required: false
        default: pnpm test -- --coverage
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  unit:
    name: Run tests and collect coverage
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
        with:
          fetch-depth: 0

      - uses: theholocron/.github/.github/actions/setup@main
        name: Setup

      - run: ${{ inputs.test-command }}
        name: Run tests with coverage

      - uses: codecov/codecov-action@v4
        name: Upload results to Codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
