name: Test

on: # yamllint disable-line rule:truthy
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  unit:
    name: Run tests and collect coverage
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        name: Checkout repository
        with:
          fetch-depth: 0

      - uses: theholocron/.github/.github/actions/setup@main
        name: Setup

      - run: pnpm test -- --coverage
        name: Run tests with coverage

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        name: Upload coverage to Codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1
        name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: '**/test-report.junit.xml'
