name: Typecheck

on:
  workflow_call:

jobs:
  typecheck:
    name: tsc --noEmit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - uses: theholocron/.github/.github/actions/setup@main
        name: Setup

      - run: pnpm typecheck
        name: Type check
