name: Typecheck

on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  typecheck:
    name: tsc --noEmit
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        name: Checkout repository

      - uses: theholocron/.github/.github/actions/setup@main
        name: Setup

      - run: pnpm typecheck
        name: Type check
