/**
 * The org's canonical `alex` (inclusive-language) config, as raw parsed
 * data rather than the pre-rendered file strings `createRcConfig()`/
 * `createIgnoreConfig()` produce for `holocron setup` to write into a
 * repo's own `.alexrc.json`/`.alexignore`.
 *
 * `.alexrc.json` is explicitly "generated by `holocron setup` — do not
 * edit manually" (this repo's own `AGENTS.md`) — the real source of truth
 * is this JSON file, one canonical copy, not each repo's synced one. A
 * central Sentinel check (holocron#769/#793) reads it directly rather
 * than fetching each repo's own copy via the Contents API — the same "one
 * config, not N copies" reasoning `@theholocron/commitlint-config` already
 * established for commit-message linting.
 */

import alexrc from "../templates/configs/alexjs/alexrc.json" with { type: "json" };

export const ALEX_CONFIG: { allow: string[] } = alexrc;

/**
 * Glob-ish path patterns `alex` skips. Kept as a literal here rather than
 * importing `../templates/configs/alexjs/alexignore` directly — that file
 * (like `commit-msg`/`pre-push`) is deliberately extensionless, matching
 * the real filename `holocron setup` writes, which ECMAScript's own
 * module resolution (`moduleResolution: "nodenext"`) can't import across
 * a package boundary without an extension. Keep in sync with that file by
 * hand; it changes rarely.
 */
export const ALEX_IGNORE_PATTERNS: string[] = [".github/*", "CHANGELOG.md", "LICENSE"];
