/**
 * The org's canonical `alex` (inclusive-language) config, as raw parsed
 * data rather than the pre-rendered file strings `createRcConfig()`/
 * `createIgnoreConfig()` produce for `holocron setup` to write into a
 * repo's own `.alexrc.json`/`.alexignore`.
 *
 * `.alexrc.json` is explicitly "generated by `holocron setup` — do not
 * edit manually" (this repo's own `AGENTS.md`) — the real source of truth
 * is this JSON file, one canonical copy, not each repo's synced one. A
 * central Sentinel check (holocron#769/#793) reads it directly rather
 * than fetching each repo's own copy via the Contents API — the same "one
 * config, not N copies" reasoning `@theholocron/commitlint-config` already
 * established for commit-message linting.
 */

import alexrc from "../templates/configs/alexjs/alexrc.json" with { type: "json" };

export const ALEX_CONFIG: { allow: string[] } = alexrc;

/**
 * Glob-ish path patterns `alex` skips. Kept as a literal here rather than
 * importing `../templates/configs/alexjs/alexignore` directly — that file
 * (like `commit-msg`/`pre-push`) is deliberately extensionless, matching
 * the real filename `holocron setup` writes, which ECMAScript's own
 * module resolution (`moduleResolution: "nodenext"`) can't import across
 * a package boundary without an extension. Keep in sync with that file by
 * hand; it changes rarely.
 */
export const ALEX_IGNORE_PATTERNS: string[] = [".github/*", "CHANGELOG.md", "LICENSE"];

/**
 * Org-defined severity for a specific flagged word — alex's `ruleId` for a
 * `retext-equality` finding *is* the word itself (e.g. `"just"`, `"easy"`),
 * confirmed directly against real alex output. Distinct from
 * `retext-profanities`' own `profanitySeverity` (a confidence rating for
 * how likely a word is used *as* profanity, not an editorial judgment
 * about the word) — this map is Sentinel's own signal for "the org has
 * already made a real call about this specific word," not alex's.
 *
 * Every word not listed here defaults to `"notice"` (unchanged from
 * today's behavior for every retext-equality finding).
 *
 * `"just"` is the one concrete case so far (holocron#865): explicitly
 * decided *not* to allow-list it — a genuine editorial call, unlike most
 * retext-equality flags, which are context-dependent, use-your-own-
 * judgment suggestions — rewording every real occurrence instead. That's
 * the "already decided this is a real problem" vs. "advisory, use
 * judgment" split this map exists to carry.
 */
export const ALEX_SEVERITY_OVERRIDES: Record<string, "notice" | "warning"> = {
	just: "warning",
};
