name: Typecheck

on: # yamllint disable-line rule:truthy
  workflow_call:
    secrets:
      TURBO_TOKEN:
        required: false

jobs:
  typecheck:
    name: tsc --noEmit
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        name: Checkout repository

      - uses: theholocron/.github/.github/actions/setup@main
        name: Setup

      - run: pnpm typecheck
        name: Type check


  conclusion:
    name: Conclusion
    runs-on: ubuntu-latest
    if: always()
    needs: [typecheck]
    steps:
      - name: Check job statuses
        run: |
          if [[ "$RESULTS" == *"failure"* ]] || [[ "$RESULTS" == *"cancelled"* ]]; then
            exit 1
          fi
        env:
          RESULTS: ${{ join(needs.*.result, ',') }}
