name: Post-release Sync

on: # yamllint disable-line rule:truthy
  release:
    types: [published]

permissions:
  contents: read

jobs:
  broadcast:
    name: Post-release Sync
    uses: theholocron/.github/.github/workflows/post-release.yml@main
    secrets: inherit
