name: Delivery

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, alpha]
  pull_request:

permissions:
  contents: read

jobs:
  bundle-size:
    name: Audit the Bundle Size
    uses: theholocron/.github/.github/workflows/delivery.bundleSize.yml@main
    secrets: inherit
