name: Repo Validation

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, alpha]
  pull_request:

permissions:
  contents: read

jobs:
  repo-validation:
    uses: theholocron/.github/.github/workflows/platform.repoValidation.yml@main
    secrets: inherit
