name: Preview

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

concurrency:
  group: preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  deployments: write
  pull-requests: write

jobs:
  preview:
    name: Preview
    uses: theholocron/.github/.github/workflows/preview.yml@main
    secrets: inherit
