name: Security

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, alpha]
  pull_request:

concurrency:
  group: security-secret-detection-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  secret-detection:
    name: Secret Detection
    uses: theholocron/.github/.github/workflows/security.secretDetection.yml@main
    secrets: inherit
