name: Source Quality

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, alpha]
  pull_request:

concurrency:
  group: source-quality-static-analysis-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  statuses: write

jobs:
  static-analysis:
    name: Static Analysis
    uses: theholocron/.github/.github/workflows/sourceQuality.staticAnalysis.yml@main
    secrets: inherit
