name: Verification

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, alpha]
  pull_request:

permissions:
  contents: read

jobs:
  performance:
    name: Audit the Performance
    uses: theholocron/.github/.github/workflows/verification.performance.yml@main
    secrets: inherit
