name: PR Bookkeeping

on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read
  pull-requests: write

jobs:
  bookkeeping:
    uses: theholocron/.github/.github/workflows/bookkeeping-pr.yml@main
    secrets: inherit
