name: Security

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  security:
    uses: theholocron/.github/.github/workflows/security.yml@main
    secrets: inherit
