name: Test

on: # yamllint disable-line rule:truthy
  push:
  pull_request:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    uses: theholocron/.github/.github/workflows/test.yml@main
    secrets: inherit
